//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbrella_Theaters_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoriums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auditoriums()
        {
            this.Screenings = new HashSet<Screenings>();
            this.Seats = new HashSet<Seats>();
        }
    
        public int AuditoriumId { get; set; }
        public string AuditoriumName { get; set; }
        public Nullable<int> TheatherId { get; set; }
    
        public virtual Theaters Theaters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Screenings> Screenings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seats> Seats { get; set; }
    }
}
