//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbrella_Theaters_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screenings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screenings()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int ScreeningId { get; set; }
        public int MovieId { get; set; }
        public int AuditoriumId { get; set; }
        public System.DateTime ViewingDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public int Price { get; set; }
        public string AddedByAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
