//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbrella_Theaters_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UmbrellaTheatersEntities : DbContext
    {
        public UmbrellaTheatersEntities()
            : base("name=UmbrellaTheatersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoriums> Auditoriums { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Screenings> Screenings { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<Theaters> Theaters { get; set; }
        public virtual DbSet<UserGenre> UserGenre { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
